version: '3.7'

services:
  url-shortener:
    container_name: url-shortener
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    environment:
      - PORT=4000
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev